local graphics = "__mining-patch-planner__/graphics/"

data:extend{
	{
		type = "sprite",
		name = "mpp_advanced_settings",
		filename = graphics.."advanced-settings.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_advanced_settings_black",
		filename = graphics.."advanced-settings-black.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_no_entity",
		filename = graphics.."no-entity.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_plus",
		filename = graphics.."plus.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_cross",
		filename = graphics.."cross.png",
		size = 64,
		mipmap_count = 2,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_blueprint_add",
		filename = graphics.."blueprint_add.png",
		size = 64,
		mipmap_count = 2,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_direction_north",
		filename = graphics.."arrow-north.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_direction_east",
		filename = graphics.."arrow-east.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_direction_south",
		filename = graphics.."arrow-south.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_direction_west",
		filename = graphics.."arrow-west.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_miner_coverage",
		filename = graphics.."miner_coverage.png",
		size = 64,
		mipmap_count = 2,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_omit_landfill",
		filename = graphics.."omit_landfill.png",
		size = 64,
		mipmap_count = 3,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_align_start",
		filename = graphics.."align_start.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_omit_deconstruct",
		filename = graphics.."omit_deconstruct.png",
		size = 64,
		mipmap_count = 2,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_no_module",
		filename = graphics.."no_module.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_show_all_miners",
		filename = graphics.."show_all_miners.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_no_pipe",
		filename = graphics.."no_pipe.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
	{
		type = "sprite",
		name = "mpp_force_pipe",
		filename = graphics.."force_pipe.png",
		size = 64,
		mipmap_count = 1,
		flags = { "icon" },
	},
}